### PR TITLE
Add ability to deidentify Patient and Coverage resources.

### PR DESCRIPTION
**Pull request by plarocque4**
This should be used to test CRD changes in the phi branch there as well.

### CODE REVIEW

**Review by yuliumitre — APPROVED** [review]
The changes look good to me.

**Review by RobertScalfani — APPROVED** [review]

**Comment by yuliumitre** [comment]
@plarocque4 Just want to clarify the button to configure "deidentify" feature. Does it work only before the patient is selected? I thought it worked when I toggled it without reselecting the topic/patient. But it doesn't seem work when I just tested it. 
Screen Shot 2022-08-12 at 2 11 02 PM

Also noticed that when "deidentified" is unchecked, the "profile" under metadata of patient and coverage under prefetch is missing. Was it like this before or do you only specify the "profile" when "deidentified" is turned on? 
Screen Shot 2022-08-12 at 2 24 09 PM

**Comment by plarocque4** [comment]
> only

The Patient and Coverage should be deidentified when the request is sent. You should see that the profile is set in the metadata and elements have been removed and modified. There is no profile in the metadata if the deidentified resources is NOT set. Whether this is set or not, there should be no difference in the result. There should only be a difference in the return noting that there is PHI in deidentified if that is actually the case.

**Comment by yuliumitre** [comment]
> > only
> 
> The Patient and Coverage should be deidentified when the request is sent. You should see that the profile is set in the metadata and elements have been removed and modified. There is no profile in the metadata if the deidentified resources is NOT set. Whether this is set or not, there should be no difference in the result. There should only be a difference in the return noting that there is PHI in deidentified if that is actually the case.

Thanks Pat for explaining it. 

This is one issue I found: when I toggled on, then toggled off the "deidentify" checkbox, the order-sign request is still sent as "deidentified" request. "Toggle on, then toggle off " once more fixes the issue. Somehow, the state is not set correctly. 

See the attached screen shot: 
Screen Shot 2022-08-15 at 9 30 05 AM

**Comment by plarocque4** [comment]
> > > only
> > 
> > 
> > The Patient and Coverage should be deidentified when the request is sent. You should see that the profile is set in the metadata and elements have been removed and modified. There is no profile in the metadata if the deidentified resources is NOT set. Whether this is set or not, there should be no difference in the result. There should only be a difference in the return noting that there is PHI in deidentified if that is actually the case.
> 
> Thanks Pat for explaining it.
> 
> This is one issue I found: when I toggled on, then toggled off the "deidentify" checkbox, the order-sign request is still sent as "deidentified" request. "Toggle on, then toggle off " once more fixes the issue. Somehow, the state is not set correctly.
> 
> See the attached screen shot: Screen Shot 2022-08-15 at 9 30 05 AM

I fixed this with my latest commit by making a deep copy of the data before modifying it. That way the original copy still contained the origin non-deidentified resources.

**Comment by yuliumitre** [comment]
@plarocque4 the fixes work well. Thanks.

**Pull request merged**
