### PR TITLE
DMEERX-668 CRD Rule for Immunosuppressive Drugs

### PR DESCRIPTION
**Pull request by yuliumitre**
This PR adds medication request supports.

### CODE REVIEW

**Comment by plarocque4** [comment]
Your editor changed lots of white space in RequestBox.js and PatientBox.js making it nearly impossible to view the diff. Is there a way you could turn some of that off? Or do you think that all of the minor changes are necessary?
I have tested the code however and it does work as written.

**Comment by plarocque4** [comment]
We probably should do something to clean up the request selection from within the patient selection. It is very cluttered now with the three different kinds of requests.

**Comment by yuliumitre** [comment]
Okay, thanks Pat. I will look into cleaning up the request selection part. I am using VS code formatter. Since we don't use this plugin in our code (Howard raised the issues a while back), the formatting makes the diff hard to compare. I will look into it and see if there is a better way to do it for now.

**Comment by plarocque4** [comment]
I'm OK with all the changes to cleanup the code to make it look better, but I'd rather that be a separate pull request. If this could include just the changes to support MedicationRequest then a second pull request could be all the white space changes and we won't have this issue in the future on these files anyway. Thanks!

**Pull request merged**
