### PR TITLE
Update the request selection

### PR DESCRIPTION
**Pull request by plarocque4**
Update the request selection to merge the DeviceRequest, ServiceRequest, and MedicationRequests into one list.
Show the display details for the code after it is selected.
Screen Shot 2020-05-22 at 3 12 55 PM

### CODE REVIEW

**Comment by lpdecelles** [comment]
image

Is this dead code?

**Comment by plarocque4** [comment]
> image
> 
> Is this dead code?

Good catch, I just removed this.

**Comment by lpdecelles** [comment]
image

Can we show the "display" instead?

makeOption(request) 
  {     
     let code = this.getCoding(request);   
     return (
      <option value={JSON.stringify(request)} key={request.id} label={code.display + " (" + code.code + ")"}>
        {code.code}
      </option>
    );
  }

**Comment by plarocque4** [comment]
> image
> 
> Can we show the "display" instead?
>
We definitely could, but I worried that some of the display strings were really long. Obviously you found a way to make it work, so just let me know what you'd like. If you choose this I should probably get rid of the details since it is just the code.display that is shown there.

**Comment by lpdecelles** [comment]
Ok, maybe where the details are we could put the request type. Thoughts?

DeviceRequest, ServiceRequest, or MedicationRequest

**Comment by plarocque4** [comment]
> Ok, maybe where the details are we could put the request type. Thoughts?
> 
> DeviceRequest, ServiceRequest, or MedicationRequest

Sure, that could work. I'll look into seeing how long they get with the display later.

**Comment by lpdecelles** [comment]
OK, we could always truncate the display to some fixed length later on.

**Review by lpdecelles — APPROVED** [review]

**Comment by plarocque4** [comment]
Screen Shot 2020-05-27 at 10 34 52 AM

**Pull request merged**
