### PR TITLE
small code cleanup changes

### PR DESCRIPTION
**Pull request by KeeyanGhoreshi**
Deals with task [273] and also includes some other minor code cleanup.

### CODE REVIEW

**Comment by lpdecelles** [comment]
image

I'm seeing an error (attached) trying to submit CRD with this branch.

**Comment by lpdecelles** [comment]
It works with Request Generator 'master', but not Request Generator 'cleanup'

**Comment by lpdecelles** [comment]
image

Here is a better pic

**Comment by KeeyanGhoreshi** [comment]
should be fixed

**Comment by lpdecelles** [comment]
Looks good.

**Pull request merged**
