### PR TITLE
Add ehr and standalone

### PR DESCRIPTION
**Pull request by KeeyanGhoreshi**
Lots of changes.  The most important one is that the EHR launch sequence has been more or less solidified.  There are still some necessary changes.

For example, due to either hardcoding or poor CQL or bad resources, only one Coverage resource works with the CRD server, so you can only use one of the patients listed in the patient list (the nameless first one) with the device request for CPAP.  

This used to not be a problem because the request generator was hard coded to use the coverage resource that came with a reference to an organization resource, which is what the CRD server seems to be looking for.  This is also the reason there is some commented out workaround code for Rush to tack on an organization resource to the request, which is also hard coded.  

Removing this, the other coverage resources in the EHR server, which the other patients use in their device requests, do not have a reference to an organization and will not produce a response from the CRD server.

Though this is titled `add-ehr-and-standalone` it is really only for EHR launch and the standalone part will be broken out into a separate task that will span all three servers (CRD, DTR, ReqGen/EHR) due to the nature of how the SMART handshake needs to be altered.  It will mostly require changes in the DTR server.

More than anything this update brings some UI updates, the most significant is the removal of the inputs that let you set patient info like age/gender.  Since you select patients from a list retrieved from the EHR, that info cannot be reasonably changed.  The DTR app will be searching through the EHR for those resources, so without write access, you cannot override the resources values for the DTR app.

One of the things that still needs to be added in a future pull request is the ability to alter the device request in the UI.  For example, selecting a different code/codeSystem, a different coverage, or even selecting a different practitioner.  Since the device request is passed through the interaction as JSON in the app context, it is persisted without the DTR app needing to reach back to the EHR, so we can safely change it with the request generator.  This is the next big task that needs to be done, so I'll put something on JIRA soon.

Also, note that this is all exclusively for stu3 (since R4 is still not supported by CRD) and will need to be updated to r4.  Luckily that should be easy given the apps new structure.

### CODE REVIEW

**Comment by plarocque4** [comment]
CRD now supports FHIR R4, but the test EHR server does not.

**Comment by plarocque4** [comment]
It appears that there are several places that are still have the ehr-server hard coded. These should all get the path to the ehr-server from the configuration window.

**Comment by plarocque4** [comment]
When you make a change in the settings (EHR Server for example) and close the settings. The change works but the value reverts when you open the settings again.

**Comment by plarocque4** [comment]
An error should probably be displayed if the EHR cannot be reached when looking for patients and DeviceRequests.

**Comment by lpdecelles** [comment]
I am seeing this error when launching the SMART App:

image

**Comment by KeeyanGhoreshi** [comment]
This is not a problem with this PR.  It is a problem with the CQL for code `94660`.  

On request generator master, `94660` is not an option in the dropdown, and Dara will autoset the code to `E0424`, which will trigger the CQL that works correctly.  If you use this branch, you can only select the patient that has the device request that uses code `94660`, so you receive this error, but the error exists on both master and this branch.

I tested this by adding `94660` to the list of codes on master branch, and sure enough selecting that code produces this error in the DTR app.  The CQL will have to be updated to fix this.  

In the meantime, if you want to test the DTR launch from this branch, you can update the device request resource in the EHR server (7. device-request.json) to use `E0424` and `loadData` to update it in the FHIR server.  This should let you launch correctly.

**Comment by hossenlopp** [comment]
That CQL error is actually not an error. It's just a warning that in the CQL to ELM translation a list result to a single entry result. I could fix that in my PR.

**Comment by KeeyanGhoreshi** [comment]
above commit deals with the X button bug I talked about before, and also deals with the bug Pat mentioned where the setting wouldn't persist when the settings button would be pressed again.  Still going to add an error message for the ehr server.

**Pull request merged**
